### ISSUE TITLE
Running a minApi26 build on Android 8.1 (API level 27) fails to start

### ISSUE THREAD

**Issue by aperezdc** [Igalia/wpe-android#60]
As I wrote in https://github.com/Igalia/wpe-android/issues/10#issuecomment-1083005419:

> The `.apk` resulting from running `./gradlew assembleMinApi26Debug -Parch=armv7` installed fine in an old 32-bit device which I had around, running LineageOS 15.1 (Oreo 8.1, API level 27), but then when starting the Minibrowser there is a backtrace from what I believe might be incorrect usage of the API compatbility libraries (probably worth a separate bug report).

Checking the logs ([full error log](https://github.com/Igalia/wpe-android/files/8380013/logcat.txt)), I see the following:

```
03-30 08:11:14.916  1108  2691 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.wpe.examples.minibrowser/.MainActivity bnds=[528,540][697,734]} from uid 10030
03-30 08:11:15.063  1108  3414 I ActivityManager: Start proc 4435:com.wpe.examples.minibrowser/u0a67 for activity com.wpe.examples.minibrowser/.MainActivity
03-30 08:11:15.088  4435  4435 I zygote  : Late-enabling -Xcheck:jni
03-30 08:11:15.425  4435  4435 I zygote  : Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
03-30 08:11:15.425  4435  4435 I zygote  :   at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2463)
03-30 08:11:15.425  4435  4435 I zygote  :   at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:938)
03-30 08:11:15.425  4435  4435 I zygote  :   at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:806)
03-30 08:11:15.425  4435  4435 I zygote  :   at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:693)
03-30 08:11:15.425  4435  4435 I zygote  :   at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:170)
03-30 08:11:15.425  4435  4435 I zygote  :   at void androidx.activity.ComponentActivity.onCreate(android.os.Bundle) (ComponentActivity.java:302)
03-30 08:11:15.425  4435  4435 I zygote  :   at void androidx.fragment.app.FragmentActivity.onCreate(android.os.Bundle) (FragmentActivity.java:273)
03-30 08:11:15.425  4435  4435 I zygote  :   at void androidx.appcompat.app.AppCompatActivity.onCreate(android.os.Bundle) (AppCompatActivity.java:115)
```

According to [this StackOverflow thread](https://stackoverflow.com/questions/51957944/android-view-viewonunhandledkeyeventlistener) it seems we are doing something fishy with the API compatibility library. I don't really understand what's going on, but the version we are using might not be suitable for our `compileSdkVersion=30` / `minSdkVersion=26` / `targetSdkVersion=30` combination.

**Comment by kele86838437** [comment]
Things like this for the crash. When loaded the ibpng16.so,  it can't locate symbol inflateValidate.
`03-30 08:11:16.551  4435  4435 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "inflateValidate" referenced by "/data/app/com.wpe.examples.minibrowser-b729ssdAuRMo3GY2x63GsA==/lib/arm/libpng16.so"...
03-30 08:11:16.551  4435  4435 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
03-30 08:11:16.552  4435  4435 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1657)`

**Comment by aperezdc** [comment]
> This can be closed as we only support API level 29 and up

Agreed, let's close the issue.
